version: 2.1
orbs:
  kube-orb: circleci/kubernetes@0.11.0
version: 2.1
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    machine: true
    environment:
      _JAVA_OPTIONS: "-Xms1024m -Xmx2048m"
      _SERVICE_OCCURENCE: 5
    steps:
      - checkout
      - run:
          name: Install Snap
          command: |
            sudo apt update
            sudo apt install snapd
      - kube-orb/install-kubectl            
      - run: ./kind-smoketest.sh
      - run:
          name: Launch Kubernetes with microk8s
          command: |
            sudo snap install microk8s --classic --channel=1.11/stable

            # wait until a k8s node is ready
            sleep 10
            n=0
            until [ $n -ge 10 ]
            do
              (/snap/bin/microk8s.kubectl get no | grep -z "Ready") && break
              n=$[$n+1]
              sleep 20
            done

            echo "Kubernetes cluster launched"

            # Allow intra-pod communication
            sudo iptables -P FORWARD ACCEPT

            echo n |/snap/bin/microk8s.enable dns registry istio

            # wait until the registry is up and running
            sleep 10
            n=0
            until [ $n -ge 10 ]
            do
              (/snap/bin/microk8s.kubectl get pod --namespace=container-registry | grep -z "Running") && break
              n=$[$n+1]
              sleep 10
            done

            echo "Kubernetes Container Registry enabled"

            # wait until istio is up and running
            sleep 10
            n=0
            until [ $n -ge 10 ]
            do
              (/snap/bin/microk8s.kubectl get pod -l istio=sidecar-injector --namespace=istio-system | grep -z "Running") && break
              n=$[$n+1]
              sleep 10
            done

            echo "Istio enabled"

            # create the namespace where the istio integration test will run

